dist: trusty
language: node_js
version: 2.0
node_js:
- node
cache:
  directories:
  - node_modules


-: &npm_deploy
    provider: npm
    edge: true
    email: goncalo05@gmail.com
    api_key: $NPM_TOKEN
    cleanup: false

deploy:
  - <<: *npm_deploy
    on:
      repo: ConsenSys/surya
      branch: master
      tags: true
  - provider: script
    script: .travis/prerelease_pu.sh
    on:
      repo: ConsenSys/surya
      branch: fix/travis-build
  - <<: *npm_deploy
    tag: next
    script: .travis/prerelease_pu.sh
    on:
      repo: ConsenSys/surya
      branch: fix/travis-build
